# week 1 functions: clean up data

#' Clean location names.
#'
#' For each string input, cleans it by stripping out the country name
#' (including the colon) and converts names to title case.
#' @param name_str A string specifying a LOCATION_NAME.
#' @returns A string. The cleaned location name.
#' @importFrom stringr str_to_title
#' @examples
#' \donttest{
#' loc_name <- "JORDAN:  BAB-A-DARAA,AL-KARAK"
#' loc_name_cleaned <- eq_location_clean(loc_name) # "Bab-A-Daraa,Al-Karak"
#' }
#' @export
eq_location_clean <- function(name_str){
  ret <- trimws(sub("(.*?): ", "", name_str))
  ret <- stringr::str_to_title(ret)
  return(ret)
}

#' Takes raw NOAA data frame and returns a clean data frame.
#'
#' The clean data frame should have the following: 1. A 'date' column created by
#' uniting the year, month, day and converting it to the Date class. 2. LATITUDE
#' and LONGITUDE columns converted to numeric class. 3. A cleaned LOCATION_NAME.
#' @param data_raw A data.frame or table specifying the raw data generated by
#' readr::read_delim
#' @returns A data.frame. The cleaned data.
#' @importFrom dplyr mutate filter
#' @importFrom magrittr %>%
#' @importFrom lubridate ymd
#' @examples
#' \dontrun{
#' data_raw <- readr::read_delim("./signif.txt")
#' data_cleaned <- eq_clean_data(data_raw)
#' }
#' @export
eq_clean_data <- function(data_raw){
  df <- data_raw %>% as.data.frame() %>%
    dplyr::mutate(date = lubridate::ymd(paste(YEAR, MONTH, DAY, sep="-"),
                                        quiet = TRUE),
                  LATITUDE = as.numeric(LATITUDE),
                  LONGITUDE = as.numeric(LONGITUDE),
                  LOCATION_NAME = eq_location_clean(LOCATION_NAME),
                  TOTAL_DEATHS = as.numeric(TOTAL_DEATHS),
                  INTENSITY = as.numeric(INTENSITY))

  return(df)
}


